spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: projectebook632@gmail.com
    password: jykbvcobdwgutebs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  mail:
    from: "projectebook632@gmail.com"
    to:  "taichikov004004@gmail.com"